[[integrations]]
name = "snooty-cache-plugin"


# Production context: all deploys from the Production branch
# set in your site’s Branches settings in the UI will inherit
# these settings.
[context.production]
  publish = "snooty/public"
  command = ". ./build.sh"
[context.deploy-preview]
  publish = "snooty/public"
  command = ". ./build.sh"
[context.branch-deploy]
  publish = "snooty/public"
  command = ". ./build.sh"
[context.dev]
  publish = "snooty/public"
  command = ". ./build.sh"


[[redirects]]
  from = "/v2.8/*"
  to = "/current/:splat"

[[redirects]]
  from = "/v2.9/*"
  to = "/current/:splat"

[[redirects]]
  from = "/master/*"
  to = "/current/:splat"


[[redirects]]
  from = "/hello/"
  to = "https://www.mongodb.com/"
  status = 200
